name: Generate Pac-Man

on:
  schedule:
    - cron: "0 */12 * * *"   # toutes les 12 h (mets "0 0 * * *" si tu veux 1/jour)
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Generate Pac-Man Contribution Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: all-all-all

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
