name: Generate Pac-Man

on:
  schedule:
    - cron: "0 */12 * * *" # tous les 12 h
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate GitHub Pac-Man Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate the Pac-Man animation
        uses: Platane/pacman@main
        with:
          github_user_name: all-all-all
          outputs: dist/github-pacman.svg

      - name: Push Pac-Man animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
